### PR TITLE
Add licence for data created by Gammapy

### PR DESCRIPTION
**Pull request by bkhelifi**
Dear all,
After the discussion made in the issue https://github.com/gammapy/gammapy/issues/4871 and https://github.com/gammapy/gammapy-data/issues/48, this PR adds the licence [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) to the folders created by our Gammapy team.

### CODE REVIEW

**Comment by bkhelifi** [comment]
@registerrier can you review this PR?

**Review by registerrier — APPROVED** [review]
Thanks @bkhelifi . Looks good.

Since most of the LICENSE files are just the same, isn't it possible to have it once (I guess in the root dir) and only use it when different from the main one.

This can be kept for a future PR anyway

**Comment by bkhelifi** [comment]
There are 8 directories and one licence for each one.  And in gammapy-data they are other directories that do not have this licence. What is the alternative you're proposing?

**Comment by registerrier** [comment]
> There are 8 directories and one licence for each one. And in gammapy-data they are other directories that do not have this licence. What is the alternative you're proposing?

If most directories use CC BY-NC-SA 4.0, we could have the license file in the main directory and README files referring to it. The main readme could also state that all content follow this license unless specified in the directory. 
We can rediscuss this later anyway.

**Pull request merged**
