### PR TITLE
Add test files for high level interface

### PR DESCRIPTION
**Pull request by Bultako**
This PR adds two simple files to test the use of `$GAMMAPY_DATA`  in config variables of the high level interface, as it is described in  https://github.com/gammapy/gammapy/pull/3377

### CODE REVIEW

**Comment by adonath** [comment]
Thanks, @Bultako! Is adding the data here really needed? The exclusion mask is already here:  https://github.com/gammapy/gammapy-data/blob/master/joint-crab/exclusion/exclusion_mask_crab.fits.gz

And the list of observations ids could be just generated in the test with a temporary file? I think adding a file for the two obs id's is not really worth it?

**Comment by Bultako** [comment]
@adonath 

Ok for the exclusion mask, but I think the observation list file is needed. If we want to fully test the PR  gammapy/gammapy#3377 I guess we need an observation list file in this `GAMMAPY_DATA` repo. Or I misunderstood  https://github.com/gammapy/gammapy/pull/3377#pullrequestreview-671004292

**Comment by adonath** [comment]
@Bultako Sorry my bad...in the case of `obs_file` I just meant adding a test _at all_. It doesn't have to use `$GAMMAPY_DATA`. I think we can be sure `make_path()` works, as we use it in many places, but form a quick look it seemed the that the `obs_file` option is not tested at all neither in `test_analysis.py` nor `test_config.py`.

**Comment by Bultako** [comment]
ok
I continue with the discussion in gammapy/gammapy#3377 and I will close this PR if no action is needed here to improve the test coverage.

**Comment by Bultako** [comment]
Closing since it is not needed in https://github.com/gammapy/gammapy/pull/337

**Pull request closed without merging**
