### PR TITLE
add 3PC catalog

### PR DESCRIPTION
**Pull request by MRegeard**
This Pull Request add the Third catalog of pulsars of Fermi-LAT. The fits file is the one taken from this web page :
https://fermi.gsfc.nasa.gov/ssc/data/access/lat/3rd_PSR_catalog/

### CODE REVIEW

**Review by QRemy — CHANGES_REQUESTED** [review]
Thanks @MRegeard, could you update the file lto the atest version : 3PC_Catalog+SEDs_20230803.fits

**Comment by QRemy** [comment]
> @QRemy Done ! Thanks for noticing on the version !

does the additionnal files need an update or not ?

**Comment by QRemy** [comment]
Do you need the profile data for 3PC ?https://fermi.gsfc.nasa.gov/ssc/data/access/lat/3rd_PSR_catalog/3PC_ProfileData_20230728.tgz

**Review by bkhelifi — APPROVED** [review]
Thanks @MRegeard ...

**Comment by MRegeard** [comment]
> Don't you need the profiles data for 3PC ?https://fermi.gsfc.nasa.gov/ssc/data/access/lat/3rd_PSR_catalog/3PC_ProfileData_20230728.tgz

Yes indeed, Thanks ! I thought I had included them ...

**Review by QRemy — APPROVED** [review]
Thanks @MRegeard, merging now

**Pull request merged**
