### PR TITLE
Add magic observation (pointlike dataset)

### PR DESCRIPTION
**Pull request by registerrier**
This PR adds the MAGIC directory into the joint-crab dataset. Only one magic observation file is added. 
This addition is small in size (220 kB) but will allow testing with pointlike datasets.

### CODE REVIEW

**Comment by adonath** [comment]
Again: should we keep the "joint-crab" folder untouched as is represents a well defined dataset? And just introduce a separate `magic-crab-pointlike` folder or similar? What do you think @Bultako?

**Comment by registerrier** [comment]
in practice the MAGIC data come the joint-crab bundle. That seemed the most natural place to put them. Of course it means that the folder is only partly filled with the initial data of the joint-crab bundle.

**Comment by Bultako** [comment]
Hi
I support @registerrier in the idea that this seems the most natural place tu add these datasets. Also I do not see the content of any of the folders of this repo fixed in time and I mostly prefer a simpler and fixed (if possible) tree-folder structure. I also remember related discussions with having different versions of `gammapy-data` and we agreed to not have it and work with small additions that do not introduce backwards incompatibilities (which is the case of this PR).

**Comment by adonath** [comment]
Even on 2nd thought I don't agree here. I think the `joint-crab` dataset is well defined and just contains already binned spectra, there is no dl3 data involved at all. And even worse the the reduced data does not have anything to do with the DL3 data added in this PR, except that that it's the same source... I would just introduce a new folder `magic-crab-pointlike` and move everything there, seems much cleaner to me. We have a similar structure for `hess-dl3-dr1` and the `joint-crab` datasets, which then contains the reduced datasets...

**Comment by Bultako** [comment]
If these datasets will be used only for testing purposes, wouldn't it make more sense to place them within the `tests` folder?

**Comment by adonath** [comment]
@Bultako I think there is maybe a good chance we will have a magic related tutorial at some point, which could use this data?

**Comment by Bultako** [comment]
Well, I would prefer to keep a cleaner structure at least at the root level, but I see we already do not keep a clear nomenclature for folder names here. In general I'm ok with any action you make as long as it keeps backwards compatibility (i.e. not changing or removing existing folder/files names)

**Comment by adonath** [comment]
I think we managed to get at least a minimal nomenclature by starting with the instrument first like `cta-`, `hess-`, `hawc-`. I agree on the backwards compatibility...

**Comment by registerrier** [comment]
OK then I change the directory to `magic-crab-pointlike`.

**Comment by adonath** [comment]
> But just to precise if that was not clear, these are the DL3 data that are used to produce the joint-crab spectra. That's why I thought it was a natural place.

Indeed this was not clear to me! I think this makes a difference, I thought it was different crab data. In this case maybe just introduce a sub-folder `joint-crab/dl3`?

**Comment by adonath** [comment]
Thanks @registerrier!

**Pull request merged**
