### PR TITLE
Changed OBS_MODE in MAGIC RAD_MAX DL3 data from WOBBLE to POINTING

### PR DESCRIPTION
**Pull request by cosimoNigro**
Hello,

as discussed with @adonath and @LauraOlivera in the dev. call, in order to simplify [#4076 in Gammapy](https://github.com/gammapy/gammapy/pull/4076), the `OBS_MODE` header keyword in the MAGIC DL3 files should be changed from `WOBBLE` to `POINTING`.

Find in the PR the new files.

I have a question though, the version of the `GADF` specs is a mandatory keyword, and in version 0.2 `OBS_MODE = WOBBLE` [was still allowed](https://gamma-astro-data-formats.readthedocs.io/en/v0.2/events/events.html#obs-mode), indeed it's what is stored in the H.E.S.S. DL3 DR1 data as well. 

Shall I change the `HDUVERS` or shall I leave it like this?
Do the H.E.S.S. DL3 files need the same change?

CC @maxnoe, as he pointed out the issue in the MAGIC converter.

P.S. I will open a follow-up pull-request changing the reference numbers in the gammapy tests using these files.

### CODE REVIEW

**Comment by maxnoe** [comment]
> I have a question though, the version of the GADF specs is a mandatory keyword, and in version 0.2 OBS_MODE = WOBBLE [was still allowed](https://gamma-astro-data-formats.readthedocs.io/en/v0.2/events/events.html#obs-mode), indeed it's what is stored in the H.E.S.S. DL3 DR1 data as well.

That's a hard question: there is no release 0.3 of GADF which clearly defines this, it's only in the current development state. But there will probably never be a GADF 0.3, instead there will be the first VODF, which might have more changes, not sure how that develops.

From the file perspective, claiming it's 0.2 is ok I think, since it was not clearly defined in 0.2. 
Putting a different version is not really ok, since there hasn't been a release.
So I'd stick with 0.2, since it's compatible with that.

**Comment by maxnoe** [comment]
Side note, I opened a discussion about making a final release of GADF before handing over to VODF: https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/issues/192

**Review by registerrier — APPROVED** [review]
Thanks @cosimoNigro !

**Review by adonath — APPROVED** [review]
Thanks @cosimoNigro!

**Pull request merged**
