### PR TITLE
Added Franceschini (2018) and Saldana-Lopez (2021) EBL models data

### PR DESCRIPTION
**Pull request by cosimoNigro**
Started to work on PR addressing 
https://github.com/gammapy/gammapy/issues/4055

I cannot read back the absorption file that I generate with the Franceschini data, I have to make some more checks.
The Saldana-Lopez one looks ok.

### CODE REVIEW

**Comment by cosimoNigro** [comment]
Done.

```python
# try to read and plot the models
import astropy.units as u
from gammapy.modeling.models import EBLAbsorptionNormSpectralModel
import matplotlib.pyplot as plt

energy_bounds = [0.08, 3] * u.TeV
opts = dict(energy_bounds=energy_bounds, xunits=u.TeV)

for z, color in zip([0.5, 1, 2, 3], ["k", "crimson", "dodgerblue", "goldenrod"]):
    ebl_franceschini = EBLAbsorptionNormSpectralModel.read("../ebl_franceschini_2018.fits.gz", redshift=z)
    ebl_saldana = EBLAbsorptionNormSpectralModel.read("../ebl_saldana-lopez_2021.fits.gz", redshift=z)
    ebl_franceschini.plot(**opts, ls="-", color=color, label=f"Franceschini (2018), z={z}")
    ebl_saldana.plot(**opts, ls="--", color=color, label=f"Saldana-Lopez (2021), z={z}")

plt.legend()
plt.ylim([1e-3, 2])
plt.show()
```
Figure_1

**Comment by cosimoNigro** [comment]
I have one question related to the original data / scripts to produce them. Should we keep them?    
Initially I had them committed but they are too large (Franceschini's original file added a million lines of code).    
I am thinking mostly in cases in which some problem is found in those files and they are to be reproduced.

**Comment by bkhelifi** [comment]
Hi @cosimoNigro,
Be able to reproduce these models seem fair and safe. @adonath or @registerrier , do you think that the underlying data could be stored as 'backup' into gamma-data? This could be a perfect place, is not it?

**Review by bkhelifi — APPROVED** [review]
Thanks @cosimoNigro. This is a great add-on

**Review by registerrier — APPROVED** [review]
Thanks @cosimoNigro . This looks good.

Maybe simply add the script that was used to create the table file and the link to the original file.

**Comment by QRemy** [comment]
Thanks @cosimoNigro, the script used to create the files can be added in a separate PR, I will merge this one so we can also merge the related PR in gammapy

**Pull request merged**
